nthduc/project-web

templates/chinhsachvadieukhoan.html
hoàn thành trang chính sách và điều khoản
=> Trang Chính Sách và Điều Khoản

templates/gioithieu.html, templates/quytrinhthanhtoan.html, templates/xacnhandonhang.html
Hoàn thành trang giới thiệu và Trang xác nhận đơn hàng
=> Trang Giới Thiệu và Trang Xác Nhận Đơn Hàng

templates/database/daisan.sql
tạo câu truy vấn queries banner
=> Câu Truy Vấn Queries banner

templates/admin/dangnhap.html
hoàn thành trang đăng nhập phần admin
=> Trang Đăng Nhập phần Admin

templates/admin/404.html, templates/admin/dangky.html, templates/admin/dangxuat.html, templates/admin/trangchu.html
hoàn thành trang đăng ký , đăng xuất cho phần admin
=> Thêm Trang Đăng Kí , Đăng Xuất cho phần Admin

templates/admin/danhsachcongtacvien.html
thêm trang danh sách cộng tác viên cho phần admin
=> Thêm trang Danh sách công tác viên cho trang Admin

templates/admin/baocaodoanhthucongtacvien.html, templates/admin/danhsachcongtacvien.html, templates/admin/trangchu.html
thêm trang danh sách cộng tác viên cho phần Admin
=> Thêm trang danh sách cộng tác viên phần Admin

templates/chinhsachbaomatthongtin.html, templates/chinhsachdoitra.html, templates/chinhsachvanchuyen.html, templates/dangnhapdangky.html, templates/gachoplat.html, templates/gioithieu.html, templates/home.html, templates/huongdandathang.html, templates/quenmatkhau.html, templates/quytrinhthanhtoan.html, templates/sango.html, templates/son.html, templates/tamoptuong.html, templates/vatlieutho.html, templates/vattunganhda.html, templates/xacnhandonhang.html
hoàn thành trang quên mật khẩu và sửa 1 vài thông tin
=> gộp nhánh từ nhánh tuấn vào nhánh chính

templates/admin/dothi.html
thêm trang đồ thi cho phần admin
=> Thêm trang Đồ thi cho trang admin

templates/cauhoithuonggap.html, templates/theodoidonhang.html, templates/thongtintaikhoan.html
thêm trang thông tin tài khoản và theo dõi đơn hàng + fix
=> thêm trang thông tin tài khoản và theo dõi đơn hàng + fix 

templates/404.html, templates/cauhoithuonggap.html, templates/chinhsachbaomatthongtin.html, templates/chinhsachdoitra.html, templates/chinhsachvadieukhoan.html, templates/chinhsachvanchuyen.html, templates/dangnhapdangky.html, templates/gachoplat.html, templates/gioithieu.html, templates/home.html, templates/huongdandathang.html, templates/huongdanthanhtoan.html, templates/lienhe.html, templates/quenmatkhau.html, templates/sango.html, templates/sanphamyeuthich.html, templates/son.html, templates/tamoptuong.html, templates/theodoidonhang.html, templates/thongtintaikhoan.html, templates/vatlieutho.html, templates/vattunganhda.html
thêm trang sản phẩm yêu thích và trang liên hệ và fix 1 số lỗi
=> Thêm trang sản phẩm yêu thích và trang liên hệ và fix 1 số lỗi

templates/admin/404.html, templates/admin/banhangthungan.html, templates/admin/baocaodoanhthucongtacvien.html, templates/admin/chatvoikhachhang.html, templates/admin/dangky.html, templates/admin/dangnhap.html, templates/admin/dangxuat.html, templates/admin/danhsachcongtacvien.html, templates/admin/danhsachdonhang.html, templates/admin/danhsachkhachhang.html, templates/admin/dothi.html, templates/admin/taikhoanadmin.html, templates/admin/themsanpham.html
fix toàn bộ link và thêm 2 trang tài khoản admin và thêm sản phẩm phần admin
=> fix toàn bộ link và thêm 2 trang tài khoản admin và thêm sản phẩm

templates/404.html, templates/cauhoithuonggap.html, templates/chinhsachbaomatthongtin.html, templates/chinhsachdoitra.html, templates/chinhsachvadieukhoan.html, templates/chinhsachvanchuyen.html, templates/cuaso.html, templates/dangnhapdangky.html, templates/daoplat.html, templates/gachoplat.html, templates/giohang.html, templates/gioithieu.html, templates/home.html, templates/huongdandathang.html, templates/huongdanthanhtoan.html, templates/lienhe.html, templates/nep.html, templates/quenmatkhau.html, templates/sango.html, templates/sanphamyeuthich.html, templates/son.html, templates/tamoptuong.html, templates/theodoidonhang.html, templates/thongtintaikhoan.html, templates/vatlieutho.html, templates/vattunganhda.html, templates/xacnhandonhang.html
fix toàn bộ link , sửa 1 số lỗi nhỏ
=> fix toàn bộ link , sửa 1 số lỗi nhỏ

templates/hangmoi.html, templates/tamoptuong.html
=> Thêm trang hàng mới

templates/cuaso.html, templates/daoplat.html, templates/database/daisan.sql, templates/giohang.html, templates/keodanxaydung.html, templates/nep.html, templates/thanhtoan.html, templates/vatlieumai.html
=> fix link css

templates/admin/404.html, templates/admin/banhangthungan.html, templates/admin/baocaodoanhthucongtacvien.html, templates/admin/chatvoikhachhang.html, templates/admin/dangky.html, templates/admin/dangnhap.html, templates/admin/dangxuat.html, templates/admin/danhsachcongtacvien.html, templates/admin/danhsachkhachhang.html, templates/admin/danhsachsanpham.html, templates/admin/quanliblog.html, templates/admin/quanlidanhmuc.html, templates/admin/taikhoanadmin.html, templates/admin/trangchu.html, templates/cuaso.html
=> thêm trang quản lí blog

templates/cuaso.html, templates/daoplat.html, templates/gachoplat.html, templates/hangmoi.html, templates/hotdeal.html, templates/keodanxaydung.html, templates/nep.html, templates/sango.html, templates/son.html, templates/tamoptuong.html, templates/vatlieumai.html, templates/vatlieutho.html, templates/vattunganhda.html
=> fix filter

.gitignore, daisan/pom.xml, daisan/src/main/java/vn/edu/hcmuaf/fit/daisan/HelloServlet.java, daisan/src/main/webapp/WEB-INF/web.xml, daisan/src/main/webapp/index.jsp
=> Khởi tạo Project JSP Servlet

daisan/src/main/java/vn/edu/hcmuaf/fit/bean/BannerBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/BlogBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/CartBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/CartItemBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/InfoBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/ItemBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/OrderBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/ProductBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/UserBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/bean/WishListBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/FindProduct.java, daisan/src/main/java/vn/edu/hcmuaf/fit/db/ConnectionDB.java
=> thêm model bean

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Filter.java, daisan/src/main/java/vn/edu/hcmuaf/fit/db/ConnectionDB.java
=> hoàn thành xử lý Lọc Filter

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Blog.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Home.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/WishList.java
=> thêm xử lí blog , wishlist

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Confirm.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Page.java
=> thêm xử lý xác nhận đơn hàng

templates/chinhsachbaohanh.html, templates/chinhsachbaomatthongtin.html, templates/chinhsachdoitra.html, templates/chinhsachvanchuyen.html, templates/huongdanthanhtoan.html
=> fix footer

templates/database/create-table.sql, templates/home.html, templates/nep.html, templates/thanhtoan.html
=> fix home and create table

daisan/src/main/java/vn/edu/hcmuaf/fit/db/DBProperties.java, daisan/src/main/resources/db.properties
db config , Database Properties
=> db config , Database Properties

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Blog.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Detail.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Filter.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Page.java, daisan/src/main/java/vn/edu/hcmuaf/fit/services/BlogService.java
Xử lí chức năng phân trang và lọc
=> Xử lí chức năng phân trang và lọc

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/AddBanner.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Blog.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Checkout.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Confirm.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/DeleteBanner.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/DeleteBlog.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/DeleteOrder.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Search.java, daisan/src/main/java/vn/edu/hcmuaf/fit/helper/BCrypt.java
thêm xử lí chức năng trong controller và tạo thêm hàm bổ trợ
=> thêm xử lí chức năng trong controller và tạo thêm hàm bổ trợ

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/AddProduct.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/QuenMatKhau.java
=> Xử lí chức năng quên mật khẩu

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Logout.java
=> Xử lí chức năng: Dăng xuất

daisan/src/main/webapp/home.jsp
=> :bug: : check user

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/admin/AdminHome.java, daisan/src/main/webapp/admin/trangchu.jsp
=> :bug: xử lý total order admin

daisan/src/main/java/vn/edu/hcmuaf/fit/controller/admin/ExtrasProfile.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/admin/PaginationProductAdmin.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/admin/UpdateAdmin.java
Xử lý Home , Phân trang sản phẩm admin
=> Xử lý Home , Phân trang sản phẩm admin

daisan/src/main/java/vn/edu/hcmuaf/fit/bean/BannerBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/Home.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/admin/ManageBanner.java, daisan/src/main/webapp/home.jsp
=> :bug: fix err

daisan/src/main/java/vn/edu/hcmuaf/fit/bean/UserBean.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/admin/AddCustomerAdmin.java, daisan/src/main/java/vn/edu/hcmuaf/fit/controller/admin/AddProductAdmin.java, daisan/src/main/java/vn/edu/hcmuaf/fit/db/ConnectionDB.java, daisan/src/main/java/vn/edu/hcmuaf/fit/services/UserService.java, daisan/src/main/webapp/admin/danhsachkhachhang.jsp, daisan/src/main/webapp/admin/danhsachsanpham.jsp
=> :bug: thêm khách hàng
